### ISSUE TITLE
Version of Keras  ?

### ISSUE THREAD

**Issue by SergeySlyusarEZlo** [gabrieldemarmiesse/KerasToCPP#1]
Hello Gabriel, Grate work!! Which version of Keras  TF and Python did you use for run this project?
Thanх!

**Comment by gabrieldemarmiesse** [comment]
To be frank I don't remember. This was mainly a way for me to do some exercices in c++. It's unmaintained at the moment. For a more serious approach, you should look into how each backend supported by keras can convert their graphs to C++
