### ISSUE TITLE
Different results in Python and  CPP

### ISSUE THREAD

**Issue by SangaRavi** [gabrieldemarmiesse/KerasToCPP#2]
Hello,

Thanks a lot for writing this repo. I am trying to replicate this in my system but the results from python inference and the cpp inference that you have provided varies. Can you please help?

Please find the inference values from python and c++ respectively,

Python : 
[[1.8702552e-07 3.4026144e-08 1.3844835e-05 1.8523424e-06 1.1318865e-08
  1.6930930e-09 4.8130622e-10 9.9993885e-01 1.3360306e-08 4.5223489e-05]]
C++ : 
Confidence of this number being 0: 3.81422%
Confidence of this number being 1: 12.9407%
Confidence of this number being 2: 10.4153%
Confidence of this number being 3: 6.08555%
Confidence of this number being 4: 16.9787%
Confidence of this number being 5: 7.98519%
Confidence of this number being 6: 17.4515%
Confidence of this number being 7: 12.9483%
Confidence of this number being 8: 9.55298%
Confidence of this number being 9: 1.82757%

Best,
Sanga

**Comment by gabrieldemarmiesse** [comment]
Hello, this project was a toy project for me to learn C++. As you can see, it's been years since the last commit. I don't recommend using it!

**Comment by SangaRavi** [comment]
Ah ok. Thanks a lot for the info.
